{% set pkgs = packages.split()|list() -%}
{% block metadata -%}
{% import 'macros/labels.jinja' as labels with context -%}
{{ labels.render_labels() }}
{% import 'macros/image_and_tag.jinja' as image_and_tag with context -%}
{{ image_and_tag.render_image_and_tag_args(
        BASE_IMAGE,
        BASE_TAG,
        pkgs,
        NEED_SPECIAL_TAGS,
        UNUSED_PARAMETERS_COMMAND,
        COMMANDS,
        ) }}
{% endblock metadata -%}
{% set builder = namespace(
        name = None,
        previous = None,
        previous_binaries_dir = BUILDER_DEFAULT_BINARIES_DIR,
        ) -%}

{% block build_stages -%}

{% import 'macros/build_stages.jinja' as build_stages -%}

{% for pkg in BUILD_STAGES|select("in", pkgs) -%}
    {{ build_stages.render_and_record_build_stage(
                                        pkg,
                                        BUILD_STAGES,
                                        builder,
                                        ) }}
{% endfor -%}

{% endblock build_stages -%}

FROM "${BASE_IMAGE}:${BASE_TAG}"

{% block runner_commands -%}
{% import 'macros/commands.jinja' as commands -%}
{{ commands.render_commands(
        pkgs,
        COMMANDS,
        COMMANDS_ORDER,
        UNUSED_PARAMETERS_COMMAND,
        RUNNER_BINARIES_DIR,
        builder) }}
{% endblock runner_commands -%}
