
{% set pkgs = packages.split() -%}

{% block metadata -%}

{# {% if packages is none -%}
{% set pkgs = NEED_EDGE + NEED_COMMUNITY + NEED_TESTING + list(NEED_BUILD_STAGE) + IN_CORE -%}
{% else -%}
{% set pkgs = packages.split() -%}
{% endif -%} #}

{% set base_tag = namespace(name=BASE_TAG) -%}

{# {% if ( pkgs|select("in", NEED_EDGE)|list()|length >= 1 or 
        pkgs|select("in", NEED_TESTING)|list()|length >= 1 ) -%}
{% set base_tag = EDGE_TAG -%}
{% endif -%} #}

{% for command_num, special_tag in NEED_SPECIAL_TAGS.items() -%}
{% if pkgs|select("in", COMMANDS[command_num].supported_parameters)|list()|length >= 1 -%}
{% set base_tag.name = special_tag -%}
{% endif -%}
{% endfor -%}

ARG BASE_IMAGE={{ BASE_IMAGE }}
ARG BASE_TAG={{ base_tag.name }}

{% endblock -%}

{% set builder = namespace(
                    name = None,
                    previous = None,
                    previous_binaries_dir = BUILDER_DEFAULT_BINARIES_DIR,
                    ) -%}

{% block build_stages -%}

{% from Dockerfile_build_stages.jinja import render_and_record_build_stage -%}

{% for pkg in BUILD_STAGES|select("in", pkgs) -%}
{{ render_and_record_build_stage(pkg, builder) }}
{% endfor -%}

{% endblock -%}

FROM "${BASE_IMAGE}:${BASE_TAG}"


{% block commands -%}

{% from Dockerfile_commands import render_commands -%}
{{ render_commands(pkgs, commands, commands_order, builder) }}

{% endblock -%}


{# {% set core_pkgs = pkgs|reject("in", NEED_BUILD_STAGE)|reject("in", NEED_TESTING)|list() -%}
{% if core_pkgs|length >= 1 -%}
RUN {{ PKG_MGR_INSTALL_FROM_DEFAULT_REPOS.format(pkgs='\\\n    ' + ' \\\n    '.join(core_pkgs)) }}

{% endif -%}

{% set testing_only_pkgs = pkgs|select("in", NEED_TESTING)|list() -%}
{% if testing_only_pkgs|length >= 1 -%}
RUN {{ PKG_MGR_INSTALL_FROM_TESTING.format(pkgs=' \\\n    ' + '\\\n    '.join(testing_only_pkgs)) }}

{% endif -%} #}