{% block metadata -%}

{% if packages is none -%}
{% set pkgs = NEED_EDGE + NEED_COMMUNITY + NEED_TESTING + list(NEED_BUILD_STAGE) + IN_CORE -%}
{% else -%}
{% set pkgs = packages.split() -%}
{% endif -%}

{% set base_tag = BASE_TAG -%}

{% if ( pkgs|select("in", NEED_EDGE)|list()|length >= 1 or 
        pkgs|select("in", NEED_TESTING)|list()|length >= 1 ) -%}
{% set base_tag = EDGE_TAG -%}
{% endif -%}

{% endblock -%}


ARG BASE_IMAGE={{ BASE_IMAGE }}
ARG BASE_TAG={{ base_tag }}

{% block build_stages -%}
{% set builder = namespace(
                    name = None,
                    previous = None,
                    previous_binaries_dir = BUILDER_DEFAULT_BINARIES_DIR,
                    ) -%}
{% from helper.jinja import add_and_record_build_stage -%}

{% for pkg in NEED_BUILD_STAGE|select("in", pkgs) -%}
{{ build_in_own_stage(pkg) }}
{% endfor -%}

{% endblock -%}

FROM "${BASE_IMAGE}:${BASE_TAG}"


{% block commands -%}

{% set core_pkgs = pkgs|reject("in", NEED_BUILD_STAGE)|reject("in", NEED_TESTING)|list() -%}
{% if core_pkgs|length >= 1 -%}
RUN {{ PKG_MGR_INSTALL_FROM_DEFAULT_REPOS.format(pkgs='\\\n    ' + ' \\\n    '.join(core_pkgs)) }}

{% endif -%}

{% set testing_only_pkgs = pkgs|select("in", NEED_TESTING)|list() -%}
{% if testing_only_pkgs|length >= 1 -%}
RUN {{ PKG_MGR_INSTALL_FROM_TESTING.format(pkgs=' \\\n    ' + '\\\n    '.join(testing_only_pkgs)) }}

{% endif -%}

{% if builder.name is not none -%}
COPY --from={{ builder.name }} {{ builder.previous_binaries_dir }} {{ RUNNER_BINARIES_DIR }}
{% endif -%}

{% endblock -%}
