FROM {{ builder_image }} as {{ builder_info.name }}

RUN apt-get update -y && \
    apt-get install -y \
    make \
    gcc \
    bzip2 \
    wget

WORKDIR {{ working_dir }}

RUN wget http://downloads.sourceforge.net/heirloom/heirloom-sh-050706.tar.bz2

RUN tar -jxvf heirloom-sh-050706.tar.bz2

RUN cd heirloom-sh-050706 && \
    make

RUN mkdir -p {{ binaries_dir }}/bin/

RUN cp heirloom-sh-050706/sh {{ binaries_dir }}/bin/heirloom-sh

