name: Test generated Dockerfiles build successfully.

on:
  workflow_dispatch:

  # pull_request:

  # push:
  #   branches:
  #     - main

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:

  lint_output:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 90

    strategy:

      fail-fast: false

      matrix:
        os: [ubuntu-22.04,] # , windows-2022, macos-12,]

    steps:

      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: 'false'


      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: Install tox
        run: pip install tox

      - name: Run docker build tests
        run: tox -e docker_build-py311
